spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: meng050319
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰to下划线自动转换
server:
  port: 8080
  address: 0.0.0.0